import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode } from "react";
import "../styles/authExperience.css";

export function AuthShell({ children, message = "Run every service with clarity.", detail = "Orders, menus, teams and daily operations — thoughtfully connected in one hospitality workspace." }: { children: ReactNode; message?: string; detail?: string }) {
  return <main className="auth-shell"><section className="auth-visual" aria-label="ServeFlow hospitality"><a className="auth-visual-brand" href="/"><img src="/serveflowlogo.png" alt="" /><span>ServeFlow</span></a><div className="auth-visual-copy"><span className="auth-kicker">Hospitality, in flow</span><h2>{message}</h2><p>{detail}</p><div className="auth-trust"><span>✓</span> Built for restaurants, cafés and hotels.</div></div></section><section className="auth-panel"><div className="auth-panel-inner">{children}</div></section></main>;
}

export function AuthCard({ children }: { children: ReactNode }) { return <div className="auth-card">{children}</div>; }
export function AuthHeader({ eyebrow, title, description }: { eyebrow?: string; title: string; description: ReactNode }) { return <header className="auth-header"><a href="/" className="auth-mobile-brand"><img src="/serveflowlogo.png" alt="" /><span>ServeFlow</span></a>{eyebrow && <span className="auth-eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{description}</p></header>; }
export function AuthInput({ label, icon, action, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; icon?: ReactNode; action?: ReactNode }) { return <label className="auth-field"><span className="auth-label">{label}</span><span className="auth-input-frame">{icon && <span className="auth-input-icon" aria-hidden="true">{icon}</span>}<input {...props} />{action}</span></label>; }
export function AuthButton({ children, ...props }: ButtonHTMLAttributes<HTMLButtonElement>) { return <button {...props} className={`auth-button ${props.className ?? ""}`}>{props.disabled && <span className="auth-spinner" aria-hidden="true" />}{children}</button>; }
export function AuthDivider({ children = "or" }: { children?: ReactNode }) { return <div className="auth-divider"><span />{children}<span /></div>; }
function GoogleMark() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.5-.2-2.2H12v4.3h5.4a4.6 4.6 0 0 1-2 3v2.8h3.3c1.9-1.8 2.9-4.4 2.9-7.9Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.7-2.4l-3.3-2.8c-.9.6-2 1-3.4 1-2.6 0-4.8-1.8-5.6-4.1H3v2.9A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.4 13.7A6 6 0 0 1 6.1 12c0-.6.1-1.2.3-1.7V7.4H3A10 10 0 0 0 2 12c0 1.6.4 3.2 1 4.6l3.4-2.9Z"/><path fill="#EA4335" d="M12 6.2c1.5 0 2.8.5 3.9 1.5l2.9-2.9A9.8 9.8 0 0 0 3 7.4l3.4 2.9C7.2 8 9.4 6.2 12 6.2Z"/></svg>; }
function GithubMark() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 .8a11.4 11.4 0 0 0-3.6 22.2c.6.1.8-.2.8-.5v-2.2c-3.4.7-4.1-1.4-4.1-1.4-.6-1.4-1.4-1.8-1.4-1.8-1.1-.8.1-.8.1-.8 1.2.1 1.9 1.3 1.9 1.3 1.1 1.9 2.9 1.3 3.6 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.3-5.5-6a4.7 4.7 0 0 1 1.2-3.2c-.1-.3-.5-1.6.1-3.2 0 0 1-.3 3.3 1.2a11.4 11.4 0 0 1 6 0c2.3-1.5 3.3-1.2 3.3-1.2.6 1.6.2 2.9.1 3.2a4.7 4.7 0 0 1 1.2 3.2c0 4.6-2.8 5.7-5.5 6 .4.4.8 1.1.8 2.2v3.3c0 .3.2.7.8.5A11.4 11.4 0 0 0 12 .8Z"/></svg>; }
export function SocialLoginButton() { return <div className="auth-social-icons" aria-label="Social authentication options"><button type="button" aria-label="Continue with Google, coming soon" aria-disabled="true" title="Google authentication is coming soon"><GoogleMark /></button><button type="button" aria-label="Continue with GitHub, coming soon" aria-disabled="true" title="GitHub authentication is coming soon"><GithubMark /></button></div>; }
export function AuthFooter({ children }: { children: ReactNode }) { return <footer className="auth-footer">{children}<span className="auth-secure">Secure access protected by ServeFlow</span></footer>; }
export function ErrorCard({ children }: { children: ReactNode }) { return <div className="auth-message auth-error" role="alert"><span>!</span><p>{children}</p></div>; }
export function SuccessCard({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <div className="auth-success"><div className="auth-success-icon" aria-hidden="true">✓</div><h1>{title}</h1><p>{children}</p>{action}</div>; }
export function PasswordStrength({ password }: { password: string }) { const score = Math.min(4, password.length < 8 ? 1 : 1 + Number(/[A-Z]/.test(password)) + Number(/[0-9]/.test(password)) + Number(/[^A-Za-z0-9]/.test(password))); const label = score < 2 ? "Needs more characters" : score < 3 ? "Fair" : score < 4 ? "Good" : "Strong"; return <div className="auth-strength" aria-live="polite"><div>{[1,2,3,4].map(level => <span key={level} className={score >= level ? "active" : ""} />)}</div><small>{label}</small></div>; }
export function LoadingOverlay({ label }: { label: string }) { return <div className="auth-loading" role="status"><span className="auth-spinner" />{label}</div>; }
