import { useMemo, useState } from "react";
import { canonicalOperationalStatus, canonicalPaymentStatus, operationalLabel, paymentLabel } from "../../../core/payment/lifecycle";
import { formatMenuPrice } from "../../qr-menu/components/menuPresentation";
import type { SmartQrPortalState } from "../types";
import "./smartCustomerPortal.css";

type Props = { state: SmartQrPortalState; calling: boolean; callStatus?: string; onViewBill: () => void; onPayBill: () => void; onCallWaiter: () => void; onSubmitFeedback: (rating: number, comment: string) => Promise<void> };
export function SmartCustomerPortal({ state, calling, callStatus, onViewBill, onPayBill, onCallWaiter, onSubmitFeedback }: Props) {
  const [billOpen,setBillOpen]=useState(false),[feedbackOpen,setFeedbackOpen]=useState(false),[rating,setRating]=useState(5),[comment,setComment]=useState(""),[feedbackBusy,setFeedbackBusy]=useState(false),[feedbackStatus,setFeedbackStatus]=useState("");
  const items=state.items??[],invoices=state.invoices??[],payment=canonicalPaymentStatus(invoices[invoices.length-1]?.status??"pending"),orderStatus=canonicalOperationalStatus(state.status);
  const orderLabel=state.display_number||state.dining_session_display_number||"Current order";
  const progress=useMemo(()=>Math.max(0,["new","accepted","preparing","ready","served"].indexOf(orderStatus)),[orderStatus]);
  return <main className="smart-customer-portal">
    <header><div className="smart-portal-brand"><span>SF</span><div><strong>{state.restaurant_name}</strong><small>Smart table service</small></div></div><span className="smart-table-pill">Table {state.table_number}</span></header>
    <section className="smart-portal-hero"><span className="smart-portal-live"><i/> Waiter service active</span><h1>Your waiter has already created your order.</h1><p>View your current bill, pay securely, or request assistance without opening another dining session.</p><div className="smart-portal-status"><div><small>Order</small><strong>{orderLabel}</strong></div><div><small>Status</small><strong>{operationalLabel(orderStatus)}</strong></div><div><small>Payment</small><strong>{paymentLabel(payment)}</strong></div></div></section>
    <section className="smart-portal-actions"><button type="button" onClick={()=>{setBillOpen(true);onViewBill();}}><span>01</span><div><strong>View Bill</strong><small>See this dining session</small></div><b>→</b></button><button type="button" className="primary" onClick={onPayBill}><span>02</span><div><strong>Pay Bill</strong><small>Owner-enabled methods only</small></div><b>→</b></button><button type="button" disabled={calling} onClick={onCallWaiter}><span>03</span><div><strong>{calling?"Calling waiter…":"Call Waiter"}</strong><small>{callStatus||"Request table assistance"}</small></div><b>→</b></button></section>
    <section className="smart-portal-progress"><div><small>Live order progress</small><strong>Updates automatically</strong></div><ol>{["Sent","Paid","Preparing","Ready","Served"].map((label,index)=><li className={index<progress?"done":index===progress?"active":""} key={label}><i/>{label}</li>)}</ol><time>Last updated {new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></section>
    {["served","closed"].includes(orderStatus)?<section className="smart-portal-feedback"><div><small>Dining session complete</small><h2>How was your experience?</h2><p>Feedback is available now that your order has been served.</p></div>{feedbackStatus?<strong role="status">{feedbackStatus}</strong>:<button type="button" onClick={()=>setFeedbackOpen(true)}>Leave Feedback</button>}</section>:null}
    {billOpen?<div className="smart-bill-overlay"><button type="button" aria-label="Close bill" onClick={()=>setBillOpen(false)}/><section role="dialog" aria-modal="true"><header><div><small>{state.restaurant_name} · Table {state.table_number}</small><h2>Your Bill</h2></div><button type="button" onClick={()=>setBillOpen(false)}>×</button></header><div className="smart-bill-items">{items.map(item=><div key={item.id}><span><strong>{item.name}</strong><small>{item.quantity} × {formatMenuPrice(item.unit_price)}</small></span><strong>{formatMenuPrice(item.line_total)}</strong></div>)}</div><dl><div><dt>Subtotal</dt><dd>{formatMenuPrice(state.subtotal??0)}</dd></div>{state.vat_amount?<div><dt>VAT</dt><dd>{formatMenuPrice(state.vat_amount)}</dd></div>:null}{state.service_charge_amount?<div><dt>Service charge</dt><dd>{formatMenuPrice(state.service_charge_amount)}</dd></div>:null}{state.discount_amount?<div><dt>Discount</dt><dd>− {formatMenuPrice(state.discount_amount)}</dd></div>:null}<div className="total"><dt>Grand total</dt><dd>{formatMenuPrice(state.grand_total??state.total_price??0)}</dd></div></dl><div className="smart-bill-actions"><button type="button" onClick={()=>setBillOpen(false)}>Back</button><button type="button" className="primary" onClick={onPayBill}>Pay Bill</button></div></section></div>:null}
    {feedbackOpen?<div className="smart-bill-overlay"><button type="button" aria-label="Close feedback" onClick={()=>setFeedbackOpen(false)}/><section role="dialog" aria-modal="true"><header><div><small>Order served</small><h2>Rate Your Experience</h2></div><button type="button" onClick={()=>setFeedbackOpen(false)}>×</button></header><div className="smart-stars">{[1,2,3,4,5].map(value=><button type="button" className={value<=rating?"active":""} aria-label={`${value} stars`} onClick={()=>setRating(value)} key={value}>★</button>)}</div><label className="smart-feedback-comment"><span>Comment <small>(Optional)</small></span><textarea maxLength={1000} value={comment} onChange={event=>setComment(event.target.value)} placeholder="Tell us what stood out…"/></label><div className="smart-bill-actions"><button type="button" onClick={()=>setFeedbackOpen(false)}>Skip</button><button type="button" className="primary" disabled={feedbackBusy} onClick={()=>{setFeedbackBusy(true);void onSubmitFeedback(rating,comment.trim()).then(()=>{setFeedbackStatus("Thank you for your feedback.");setFeedbackOpen(false);}).catch(error=>setFeedbackStatus(error instanceof Error?error.message:"Feedback could not be submitted.")).finally(()=>setFeedbackBusy(false));}}>{feedbackBusy?"Submitting…":"Submit Feedback"}</button></div></section></div>:null}
  </main>;
}
