-- Phase O10.2: verified-data Sales, Inventory and AI BI module services.
create or replace function public.get_owner_sales_module_report(target_restaurant_id uuid,range_start timestamptz,range_end timestamptz) returns jsonb language sql stable security definer set search_path=public as $$
with paid as(select i.* from order_invoices i where i.restaurant_id=target_restaurant_id and i.status in('paid','verified') and i.verified_at>=range_start and i.verified_at<range_end), refunds as(select count(*)::int count,coalesce(sum(total_price),0)::numeric value from order_invoices where restaurant_id=target_restaurant_id and status='refunded' and verified_at>=range_start and verified_at<range_end), hours as(select extract(hour from verified_at)::int hour_of_day,count(*)::int orders,sum(total_price)::numeric revenue from paid group by 1), methods as(select coalesce(payment_method,'Other') method,count(*)::int invoices,sum(total_price)::numeric revenue from paid group by 1), totals as(select coalesce(sum(total_price),0)::numeric revenue,count(*)::int orders from paid)
select jsonb_build_object('summary',jsonb_build_array(jsonb_build_object('metric','Revenue','value',t.revenue),jsonb_build_object('metric','Orders','value',t.orders),jsonb_build_object('metric','Average Bill','value',case when t.orders=0 then 0 else t.revenue/t.orders end),jsonb_build_object('metric','Refunds','value',r.value)), 'top_hours',coalesce((select jsonb_agg(to_jsonb(h) order by revenue desc) from (select * from hours order by revenue desc limit 5) h),'[]'::jsonb),'payment_breakdown',coalesce((select jsonb_agg(to_jsonb(m) order by revenue desc) from methods m),'[]'::jsonb)) from totals t cross join refunds r where public.owner_can_report(target_restaurant_id);
$$;
create or replace function public.get_owner_inventory_module_report(target_restaurant_id uuid,range_start timestamptz,range_end timestamptz) returns jsonb language sql stable security definer set search_path=public as $$
with paid as(select id from order_invoices where restaurant_id=target_restaurant_id and status in('paid','verified') and verified_at>=range_start and verified_at<range_end), demand as(select ingredient,sum(oi.quantity)::int usage_units from paid p join order_items oi on oi.invoice_id=p.id join menu_items m on m.id=oi.menu_item_id cross join lateral unnest(coalesce(m.ingredients,array[]::text[])) ingredient group by ingredient)
select jsonb_build_object('rows',coalesce(jsonb_agg(jsonb_build_object('ingredient',ingredient,'estimated_usage',usage_units,'forecast',case when usage_units>=20 then 'High demand — review stock' when usage_units>=8 then 'Monitor stock' else 'Stable' end) order by usage_units desc),'[]'::jsonb),'note','Inventory quantities are not stored; this is verified-sales ingredient demand, not a stock balance.') from demand where public.owner_can_report(target_restaurant_id);
$$;
create or replace function public.get_owner_ai_business_insights(target_restaurant_id uuid,range_start timestamptz,range_end timestamptz) returns jsonb language sql stable security definer set search_path=public as $$
with bounds as(select range_end-range_start span), current_paid as(select i.*,o.table_number from order_invoices i join orders o on o.id=i.order_id where i.restaurant_id=target_restaurant_id and i.status in('paid','verified') and i.verified_at>=range_start and i.verified_at<range_end), previous_paid as(select i.* from order_invoices i,bounds b where i.restaurant_id=target_restaurant_id and i.status in('paid','verified') and i.verified_at>=range_start-b.span and i.verified_at<range_start), totals as(select coalesce((select sum(total_price) from current_paid),0)::numeric current_revenue,coalesce((select sum(total_price) from previous_paid),0)::numeric previous_revenue), best_table as(select table_number,sum(total_price) revenue from current_paid where table_number is not null group by table_number order by revenue desc limit 1), busiest as(select extract(hour from verified_at)::int hour_of_day,count(*) orders from current_paid group by 1 order by orders desc limit 1), refund_stats as(select count(*) count from order_invoices where restaurant_id=target_restaurant_id and status='refunded' and verified_at>=range_start and verified_at<range_end)
select jsonb_build_object('insights',jsonb_build_array(jsonb_build_object('type','summary','title','Revenue trend','detail',case when previous_revenue=0 then 'No prior-period revenue is available for comparison.' else format('Revenue %s %s%% compared with the previous period.',case when current_revenue>=previous_revenue then 'increased' else 'decreased' end,round(abs((current_revenue-previous_revenue)/previous_revenue*100),1)) end),jsonb_build_object('type','opportunity','title','Most profitable table','detail',coalesce((select format('Table %s generated the highest verified revenue.',table_number) from best_table),'No table revenue is available yet.')),jsonb_build_object('type','operations','title','Busiest hour','detail',coalesce((select format('%s:00–%s:00 was the busiest verified sales hour.',hour_of_day,hour_of_day+1) from busiest),'No busy-hour pattern is available yet.')),jsonb_build_object('type',case when refund_stats.count>2 then 'warning' else 'control' end,'title','Refund activity','detail',format('%s refunded invoice(s) were recorded in this period.',refund_stats.count)),jsonb_build_object('type','forecast','title','Closing revenue direction','detail',case when current_revenue>=previous_revenue then 'Current verified revenue is tracking at or above the previous period.' else 'Current verified revenue is tracking below the previous period; review traffic and payment mix.' end))) from totals cross join refund_stats where public.owner_can_report(target_restaurant_id);
$$;
revoke all on function public.get_owner_sales_module_report(uuid,timestamptz,timestamptz),public.get_owner_inventory_module_report(uuid,timestamptz,timestamptz),public.get_owner_ai_business_insights(uuid,timestamptz,timestamptz) from public,anon;
grant execute on function public.get_owner_sales_module_report(uuid,timestamptz,timestamptz),public.get_owner_inventory_module_report(uuid,timestamptz,timestamptz),public.get_owner_ai_business_insights(uuid,timestamptz,timestamptz) to authenticated,service_role;
