alter table public.inventory_items add column if not exists supplier_name text;
alter table public.inventory_items add column if not exists supplier_lead_days integer not null default 1 check (supplier_lead_days between 0 and 365);

create table if not exists public.inventory_stock_events(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,inventory_item_id uuid not null references public.inventory_items(id) on delete cascade,actor_staff_id uuid not null references public.restaurant_staff(id),event_type text not null check(event_type in('catalog_created','stock_updated')),previous_quantity numeric,new_quantity numeric,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.inventory_stock_events enable row level security;
drop policy if exists inventory_stock_events_read on public.inventory_stock_events;
create policy inventory_stock_events_read on public.inventory_stock_events for select to authenticated using(public.inventory_workflow_has_role(restaurant_id,array['owner','manager','inventory']));
grant select on public.inventory_stock_events to authenticated;

create or replace function public.upsert_inventory_item(target_restaurant_id uuid,target_item_id uuid,target_name text,target_unit text,target_current_quantity numeric,target_reorder_level numeric,target_supplier_name text default null,target_supplier_lead_days integer default 1)
returns uuid language plpgsql security definer set search_path=public as $$ declare actor public.restaurant_staff; result_id uuid; previous_qty numeric; event_name text; begin
select * into actor from public.restaurant_staff where restaurant_id=target_restaurant_id and user_id=auth.uid() and active=true and role::text in('inventory','owner') limit 1;if actor.id is null then raise exception 'Inventory catalog access denied.';end if;
if btrim(coalesce(target_name,''))='' or btrim(coalesce(target_unit,''))='' or target_current_quantity<0 or target_reorder_level<0 then raise exception 'Inventory item values are invalid.';end if;
if target_item_id is null then insert into public.inventory_items(restaurant_id,name,unit,current_quantity,reorder_level,supplier_name,supplier_lead_days) values(target_restaurant_id,btrim(target_name),btrim(target_unit),target_current_quantity,target_reorder_level,nullif(btrim(coalesce(target_supplier_name,'')),''),coalesce(target_supplier_lead_days,1)) returning id into result_id;event_name:='catalog_created';
else select current_quantity into previous_qty from public.inventory_items where id=target_item_id and restaurant_id=target_restaurant_id for update;if not found then raise exception 'Inventory item not found.';end if;update public.inventory_items set name=btrim(target_name),unit=btrim(target_unit),current_quantity=target_current_quantity,reorder_level=target_reorder_level,supplier_name=nullif(btrim(coalesce(target_supplier_name,'')),''),supplier_lead_days=coalesce(target_supplier_lead_days,1),updated_at=now() where id=target_item_id;result_id:=target_item_id;event_name:='stock_updated';end if;
insert into public.inventory_stock_events(restaurant_id,inventory_item_id,actor_staff_id,event_type,previous_quantity,new_quantity,details) values(target_restaurant_id,result_id,actor.id,event_name,previous_qty,target_current_quantity,jsonb_build_object('name',btrim(target_name),'unit',btrim(target_unit),'reorder_level',target_reorder_level,'supplier_name',nullif(btrim(coalesce(target_supplier_name,'')),''),'supplier_lead_days',target_supplier_lead_days));return result_id;end $$;

create or replace function public.get_inventory_intelligence(target_restaurant_id uuid)
returns jsonb language sql stable security definer set search_path=public as $$
with guard as(select public.inventory_workflow_has_role(target_restaurant_id,array['owner','manager','inventory','kitchen']) allowed),usage as(select inventory_item_id,sum(quantity) filter(where delivered_at>=now()-interval '7 days') seven_day,sum(quantity) filter(where delivered_at>=now()-interval '28 days') twenty_eight_day from public.kitchen_inventory_requests,guard where guard.allowed and restaurant_id=target_restaurant_id and status='delivered' and inventory_item_id is not null group by inventory_item_id),demand as(select inventory_item_id,sum(quantity) open_demand from public.kitchen_inventory_requests,guard where guard.allowed and restaurant_id=target_restaurant_id and status in('pending','accepted') and inventory_item_id is not null group by inventory_item_id),base as(select i.*,coalesce(u.seven_day,0) weekly_consumption,coalesce(u.seven_day,0)/7 daily_consumption,coalesce(u.twenty_eight_day,0) monthly_consumption,coalesce(d.open_demand,0) kitchen_demand from public.inventory_items i cross join guard left join usage u on u.inventory_item_id=i.id left join demand d on d.inventory_item_id=i.id where guard.allowed and i.restaurant_id=target_restaurant_id and i.active),ranked as(select *,percent_rank() over(order by weekly_consumption) velocity_rank from base)
select case when not exists(select 1 from guard where allowed) then jsonb_build_object('error','Permission denied.') else coalesce((select jsonb_agg(jsonb_build_object('id',id,'name',name,'unit',unit,'current_quantity',current_quantity,'reorder_level',reorder_level,'supplier_name',supplier_name,'supplier_lead_days',supplier_lead_days,'daily_consumption',round(daily_consumption,3),'weekly_consumption',weekly_consumption,'monthly_consumption',monthly_consumption,'remaining_hours',case when daily_consumption>0 then round(current_quantity/daily_consumption*24,1) else null end,'suggested_reorder_at',case when daily_consumption>0 then now()+greatest(0,(current_quantity-reorder_level)/daily_consumption)*interval '1 day'-supplier_lead_days*interval '1 day' else null end,'movement',case when weekly_consumption=0 then 'no_history' when velocity_rank>=.67 then 'fast' when velocity_rank<=.33 then 'slow' else 'normal' end,'health',case when current_quantity<=reorder_level then 'critical' when current_quantity<=reorder_level*2 then 'low' when current_quantity<=reorder_level*3 then 'normal' else 'healthy' end,'supplier_reminder',current_quantity<=reorder_level*2,'kitchen_demand',kitchen_demand) order by current_quantity<=reorder_level desc,weekly_consumption desc) from ranked),'[]'::jsonb) end $$;
revoke all on function public.upsert_inventory_item(uuid,uuid,text,text,numeric,numeric,text,integer) from public,anon;revoke all on function public.get_inventory_intelligence(uuid) from public,anon;grant execute on function public.upsert_inventory_item(uuid,uuid,text,text,numeric,numeric,text,integer) to authenticated,service_role;grant execute on function public.get_inventory_intelligence(uuid) to authenticated,service_role;
