-- Replace the PostgreSQL formatting function in the AI insight path with typed concatenation.
-- This avoids runtime placeholder-count failures for every data shape.
create or replace function public.get_owner_ai_business_insights(target_restaurant_id uuid,range_start timestamptz,range_end timestamptz) returns jsonb language sql stable security definer set search_path=public as $$
with bounds as(select range_end-range_start span), current_paid as(select i.*,o.table_number from order_invoices i join orders o on o.restaurant_id=i.restaurant_id and o.id=i.order_id where i.restaurant_id=target_restaurant_id and i.payment_status::text in('paid','refunded') and i.paid_at>=range_start and i.paid_at<range_end), previous_paid as(select i.* from order_invoices i,bounds b where i.restaurant_id=target_restaurant_id and i.payment_status::text in('paid','refunded') and i.paid_at>=range_start-b.span and i.paid_at<range_start), totals as(select coalesce((select sum(total_price) from current_paid),0)::numeric current_revenue,coalesce((select sum(total_price) from previous_paid),0)::numeric previous_revenue), best_table as(select table_number,sum(total_price) revenue from current_paid where table_number is not null group by table_number order by revenue desc limit 1), busiest as(select extract(hour from paid_at)::int hour_of_day,count(*) orders from current_paid group by 1 order by orders desc limit 1), refund_stats as(select count(*) count from current_paid where payment_status::text='refunded')
select jsonb_build_object('insights',jsonb_build_array(jsonb_build_object('type','summary','title','Revenue trend','detail',case when previous_revenue=0 then 'No prior-period revenue is available for comparison.' else 'Revenue '||(case when current_revenue>=previous_revenue then 'increased' else 'decreased' end)||' '||round(abs((current_revenue-previous_revenue)/previous_revenue*100),1)::text||'% compared with the previous period.' end),jsonb_build_object('type','opportunity','title','Most profitable table','detail',coalesce((select 'Table '||table_number::text||' generated the highest collected revenue.' from best_table),'No table revenue is available yet.')),jsonb_build_object('type','operations','title','Busiest collection hour','detail',coalesce((select hour_of_day::text||':00–'||(hour_of_day+1)::text||':00 was the busiest collection hour.' from busiest),'No collection-hour pattern is available yet.')),jsonb_build_object('type',case when refund_stats.count>2 then 'warning' else 'control' end,'title','Refund activity','detail',refund_stats.count::text||' refunded invoice(s) were recorded in this period.'))) from totals cross join refund_stats where public.owner_can_report(target_restaurant_id);
$$;

revoke all on function public.get_owner_ai_business_insights(uuid,timestamptz,timestamptz) from public,anon;
grant execute on function public.get_owner_ai_business_insights(uuid,timestamptz,timestamptz) to authenticated,service_role;
